server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/GM_System?createDatabaseIfNotExist=true
    username: /
    password: /

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true